name: Docker Multi-Arch Build & Publish

on:
  push:
    tags:
      - 'v*.*.*'          # 触发条件：git tag v1.0.0
  workflow_dispatch:      # 手动触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU (支持 arm)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate tags
        id: meta
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "image=ghcr.io/${{ github.repository_owner }}/printer-pro" >> $GITHUB_OUTPUT

      - name: Build & Push Multi-Arch
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ${{ steps.meta.outputs.image }}:latest
            ${{ steps.meta.outputs.image }}:latest-amd64
            ${{ steps.meta.outputs.image }}:latest-arm64
            ${{ steps.meta.outputs.image }}:latest-armv7
            ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.version }}
            ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.version }}-amd64
            ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.version }}-arm64
            ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.version }}-armv7
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Print success
        run: |
          echo "镜像已发布！"
          echo "x86:     ghcr.io/${{ github.repository_owner }}/printer-pro:latest-amd64"
          echo "树莓派4: ghcr.io/${{ github.repository_owner }}/printer-pro:latest-arm64"
          echo "树莓派1-3: ghcr.io/${{ github.repository_owner }}/printer-pro:latest-armv7"